### PR TITLE
Upgrade to smtp-server and using TLS

### PR DESCRIPTION
**Pull request by koyaan**

### CODE REVIEW

**Comment by michielbdejong** [comment]
Hah, thanks! I had forgotten I even once wrote this repo :) I used to use it to get startssl certs, and for that use-case, it would create a chicken-and-egg problem to run this mailtrap with TLS :) But sure, it's cool if it can support TLS, for other use-cases! :)

Just one remark - your new instructions in the readme generate a csr, but don't add a step for actually getting the cert signed, right? A TLS cert for an smtp server would have to be signed for sending servers to trust it, right? or would they generally accept a self-signed one? If my email doesn't arrive because my TLS cert is not signed, then I would prefer to run the mailtrap without TLS...

So if you either:
- add a note in the readme pointing to some evidence that self-signed certs on smtp servers are a good idea,

or:
- add a line in the readme stating that you have to get the csr signed somehow (I don't think letsencrypt supports any smtp-based acme challenges yet?), or otherwise fall back to non-TLS smtp (is that still possible after your changes?)

then I'll accept your PR! :) thanks for contributing!

**Comment by koyaan** [comment]
Hi @michielbdejong i updated my fork https://github.com/koyaan/mailtrap to auto-generate Cert on run, and gave customization options via Env vars, but i´m not sure merging is really a good idea, since we solve 2 different problems.

I guess I could add a switch to either listen plain on 25 or with TLS on 435.

What do you think?

**Comment by michielbdejong** [comment]
I mentioned your fork in the readme, see https://github.com/michielbdejong/mailtrap/commit/b3b6689c4c09165ec9a42518b782ba11d08fe24e
Maybe that's the easiest solution, so then we just keep them separate and close this PR?

**Comment by koyaan** [comment]
@michielbdejong sounds great, thank your for the mention!

**Pull request closed without merging**
